export const mockClients = [
  {
    id: '1',
    company: 'FitZone Gym',
    industry: 'Fitness & Health',
    status: 'active',
    contact: 'Sarah Chen',
    email: 'sarah@fitzone.com',
    phone: '+1 (555) 123-4567',
    location: 'San Francisco, CA',
    logo: 'FZ',
    progress: 78,
    description: 'FitZone Gym is a premium fitness center chain with 12 locations across the Bay Area. They specialize in personal training, group classes, and nutrition coaching.',
    metrics: [
      { label: 'Content Pieces', value: '156', change: '+18%', up: true },
      { label: 'Active Campaigns', value: '4', change: '0%', up: true },
      { label: 'Engagement Rate', value: '4.8%', change: '+0.6%', up: true },
      { label: 'Leads Generated', value: '892', change: '+24%', up: true },
    ],
    workflows: [
      { name: 'Social Media Campaign', status: 'running', progress: 72, lastRun: '2 hours ago' },
      { name: 'Blog Content Pipeline', status: 'running', progress: 45, lastRun: '1 day ago' },
      { name: 'Email Newsletter', status: 'paused', progress: 90, lastRun: '5 days ago' },
    ],
    recentActivity: [
      { action: 'Instagram post published - "Leg Day Tips"', time: '1 hour ago' },
      { action: 'Weekly analytics report generated', time: '3 hours ago' },
      { action: 'Email campaign sent to 2,450 subscribers', time: '1 day ago' },
      { action: 'Blog post "5 Benefits of Personal Training" published', time: '2 days ago' },
    ],
    contentStats: [
      { label: 'Blog Posts', value: 48, color: 'text-blue-400' },
      { label: 'Social Posts', value: 124, color: 'text-emerald-400' },
      { label: 'Emails', value: 36, color: 'text-purple-400' },
      { label: 'Videos', value: 18, color: 'text-rose-400' },
    ],
    campaigns: [
      { name: 'Summer Fitness Challenge', status: 'active', budget: 2500, impressions: '45.2K', clicks: '2.1K' },
      { name: 'New Year Promotion', status: 'completed', budget: 3000, impressions: '82.1K', clicks: '3.8K' },
    ],
  },
  {
    id: '2',
    company: 'Urban Cafe',
    industry: 'Food & Beverage',
    status: 'active',
    contact: 'Marcus Johnson',
    email: 'marcus@urbancafe.com',
    phone: '+1 (555) 234-5678',
    location: 'New York, NY',
    logo: 'UC',
    progress: 92,
    description: 'Urban Cafe is a trendy coffee shop chain with 8 locations in Manhattan. Known for artisanal coffee, pastries, and a cozy workspace atmosphere.',
    metrics: [
      { label: 'Content Pieces', value: '98', change: '+12%', up: true },
      { label: 'Active Campaigns', value: '3', change: '+1', up: true },
      { label: 'Engagement Rate', value: '6.2%', change: '+1.1%', up: true },
      { label: 'Leads Generated', value: '445', change: '+15%', up: true },
    ],
    workflows: [
      { name: 'Instagram Automation', status: 'running', progress: 88, lastRun: '30 min ago' },
      { name: 'Blog Content Pipeline', status: 'running', progress: 65, lastRun: '1 day ago' },
      { name: 'Loyalty Email Campaign', status: 'running', progress: 40, lastRun: '3 hours ago' },
    ],
    recentActivity: [
      { action: 'Instagram story posted - "New Latte Art"', time: '30 min ago' },
      { action: 'Weekly analytics report generated', time: '2 hours ago' },
      { action: 'Email campaign sent to 3,200 subscribers', time: '6 hours ago' },
      { action: 'Blog post "Best Coffee Spots in NYC" published', time: '1 day ago' },
    ],
    contentStats: [
      { label: 'Blog Posts', value: 32, color: 'text-blue-400' },
      { label: 'Social Posts', value: 210, color: 'text-emerald-400' },
      { label: 'Emails', value: 28, color: 'text-purple-400' },
      { label: 'Videos', value: 45, color: 'text-rose-400' },
    ],
    campaigns: [
      { name: 'Holiday Blend Launch', status: 'active', budget: 1800, impressions: '28.4K', clicks: '1.6K' },
    ],
  },
  {
    id: '3',
    company: 'TechFlow SaaS',
    industry: 'Technology',
    status: 'paused',
    contact: 'Priya Patel',
    email: 'priya@techflow.io',
    phone: '+1 (555) 345-6789',
    location: 'Austin, TX',
    logo: 'TF',
    progress: 45,
    description: 'TechFlow is a B2B SaaS platform that provides workflow automation tools for mid-size enterprises. They serve over 500 companies worldwide.',
    metrics: [
      { label: 'Content Pieces', value: '67', change: '+5%', up: true },
      { label: 'Active Campaigns', value: '2', change: '-1', up: false },
      { label: 'Engagement Rate', value: '3.1%', change: '-0.4%', up: false },
      { label: 'Leads Generated', value: '234', change: '+8%', up: true },
    ],
    workflows: [
      { name: 'Drip Email Sequence', status: 'paused', progress: 78, lastRun: '3 days ago' },
      { name: 'LinkedIn Outreach', status: 'paused', progress: 34, lastRun: '1 week ago' },
    ],
    recentActivity: [
      { action: 'Campaign paused due to budget review', time: '3 days ago' },
      { action: 'Q2 performance report generated', time: '5 days ago' },
      { action: 'Email sequence performance reviewed', time: '1 week ago' },
    ],
    contentStats: [
      { label: 'Blog Posts', value: 24, color: 'text-blue-400' },
      { label: 'Social Posts', value: 56, color: 'text-emerald-400' },
      { label: 'Emails', value: 42, color: 'text-purple-400' },
      { label: 'Videos', value: 8, color: 'text-rose-400' },
    ],
    campaigns: [
      { name: 'Enterprise Lead Gen', status: 'paused', budget: 5000, impressions: '12.3K', clicks: '534' },
    ],
  },
  {
    id: '4',
    company: 'Bloom Beauty',
    industry: 'Beauty & Cosmetics',
    status: 'active',
    contact: 'Emily Rose',
    email: 'emily@bloombeauty.com',
    phone: '+1 (555) 456-7890',
    location: 'Los Angeles, CA',
    logo: 'BB',
    progress: 64,
    description: 'Bloom Beauty is a clean beauty brand offering skincare and makeup products made from organic, sustainable ingredients. Popular among eco-conscious consumers.',
    metrics: [
      { label: 'Content Pieces', value: '203', change: '+32%', up: true },
      { label: 'Active Campaigns', value: '5', change: '+2', up: true },
      { label: 'Engagement Rate', value: '8.9%', change: '+2.3%', up: true },
      { label: 'Leads Generated', value: '1,245', change: '+41%', up: true },
    ],
    workflows: [
      { name: 'Instagram Automation', status: 'running', progress: 71, lastRun: '1 hour ago' },
      { name: 'Influencer Outreach', status: 'running', progress: 55, lastRun: '5 hours ago' },
      { name: 'Blog Content Pipeline', status: 'running', progress: 33, lastRun: '1 day ago' },
      { name: 'Email Newsletter', status: 'paused', progress: 92, lastRun: '4 days ago' },
    ],
    recentActivity: [
      { action: 'Instagram post published - "Summer Glow Routine"', time: '1 hour ago' },
      { action: 'Influencer partnership confirmed with @skincarebyjade', time: '5 hours ago' },
      { action: 'Blog post "10 Clean Beauty Tips" published', time: '1 day ago' },
      { action: 'Weekly analytics report generated', time: '2 days ago' },
    ],
    contentStats: [
      { label: 'Blog Posts', value: 52, color: 'text-blue-400' },
      { label: 'Social Posts', value: 312, color: 'text-emerald-400' },
      { label: 'Emails', value: 44, color: 'text-purple-400' },
      { label: 'Videos', value: 28, color: 'text-rose-400' },
    ],
    campaigns: [
      { name: 'Summer Collection Launch', status: 'active', budget: 4500, impressions: '89.3K', clicks: '4.7K' },
      { name: 'Influencer Campaign', status: 'active', budget: 6000, impressions: '124.5K', clicks: '6.2K' },
    ],
  },
  {
    id: '5',
    company: 'PeakPerformance',
    industry: 'Sports & Coaching',
    status: 'onboarding',
    contact: 'Alex Rivera',
    email: 'alex@peakperf.com',
    phone: '+1 (555) 567-8901',
    location: 'Denver, CO',
    logo: 'PP',
    progress: 23,
    description: 'PeakPerformance provides athletic training programs and sports coaching for amateur and semi-professional athletes. They offer both in-person and virtual coaching.',
    metrics: [
      { label: 'Content Pieces', value: '12', change: '+100%', up: true },
      { label: 'Active Campaigns', value: '1', change: '+1', up: true },
      { label: 'Engagement Rate', value: '0%', change: 'New', up: true },
      { label: 'Leads Generated', value: '45', change: '+45', up: true },
    ],
    workflows: [
      { name: 'Workflow Setup', status: 'running', progress: 23, lastRun: 'Just now' },
    ],
    recentActivity: [
      { action: 'Client onboarded successfully', time: 'Just now' },
      { action: 'Initial brand audit completed', time: '1 hour ago' },
      { action: 'Social media accounts connected', time: '3 hours ago' },
    ],
    contentStats: [
      { label: 'Blog Posts', value: 3, color: 'text-blue-400' },
      { label: 'Social Posts', value: 8, color: 'text-emerald-400' },
      { label: 'Emails', value: 1, color: 'text-purple-400' },
      { label: 'Videos', value: 0, color: 'text-rose-400' },
    ],
    campaigns: [],
  },
  {
    id: '6',
    company: 'GreenLeaf Organics',
    industry: 'Organic Food',
    status: 'active',
    contact: 'Jordan Kim',
    email: 'jordan@greenleaf.com',
    phone: '+1 (555) 678-9012',
    location: 'Portland, OR',
    logo: 'GO',
    progress: 55,
    description: 'GreenLeaf Organics is a farm-to-table organic food company offering fresh produce, meal kits, and pantry staples delivered directly to consumers.',
    metrics: [
      { label: 'Content Pieces', value: '87', change: '+14%', up: true },
      { label: 'Active Campaigns', value: '3', change: '0%', up: true },
      { label: 'Engagement Rate', value: '5.4%', change: '+0.8%', up: true },
      { label: 'Leads Generated', value: '678', change: '+22%', up: true },
    ],
    workflows: [
      { name: 'Social Media Campaign', status: 'running', progress: 61, lastRun: '3 hours ago' },
      { name: 'Blog Content Pipeline', status: 'running', progress: 48, lastRun: '1 day ago' },
      { name: 'Email Newsletter', status: 'running', progress: 35, lastRun: '2 days ago' },
    ],
    recentActivity: [
      { action: 'Instagram post published - "Farm Fresh Thursday"', time: '3 hours ago' },
      { action: 'Blog post "Benefits of Organic Eating" published', time: '1 day ago' },
      { action: 'Email newsletter sent to 5,800 subscribers', time: '2 days ago' },
      { action: 'Weekly analytics report generated', time: '3 days ago' },
    ],
    contentStats: [
      { label: 'Blog Posts', value: 38, color: 'text-blue-400' },
      { label: 'Social Posts', value: 145, color: 'text-emerald-400' },
      { label: 'Emails', value: 32, color: 'text-purple-400' },
      { label: 'Videos', value: 12, color: 'text-rose-400' },
    ],
    campaigns: [
      { name: 'Seasonal Produce Campaign', status: 'active', budget: 2200, impressions: '34.8K', clicks: '1.9K' },
    ],
  },
]

export const mockAgents = [
  { id: 'openclaw', name: 'OpenClaw', icon: 'Search', desc: 'Lead Generation — research, prospects, outreach', status: 'online', category: 'Team' },
  { id: 'hermes', name: 'Hermes', icon: 'MessageSquare', desc: 'Client Management — onboarding, communication, delivery', status: 'online', category: 'Team' },
  { id: 'aca', name: 'ACA (CEO Agent)', icon: 'Briefcase', desc: 'Central Coordinator — analyzes requirements, assigns to right agents', status: 'online', category: 'Team' },
  { id: 'opencode', name: 'OpenCode', icon: 'Code', desc: 'Agency Core — builds full package (content, email, ads, video, website)', status: 'online', category: 'Team' },
  { id: 'contentwriter', name: 'ContentWriter', icon: 'PenTool', desc: 'Crafts blog posts, articles, and web copy', status: 'online', category: 'Content' },
  { id: 'emailwizard', name: 'EmailWizard', icon: 'Mail', desc: 'Designs and writes email campaigns', status: 'online', category: 'Content' },
  { id: 'seomaster', name: 'SEOMaster', icon: 'SearchIcon', desc: 'Optimizes content for search engines', status: 'busy', category: 'Content' },
  { id: 'socialcommander', name: 'SocialCommander', icon: 'Globe', desc: 'Manages multi-platform social presence', status: 'online', category: 'Social' },
  { id: 'calendarmaster', name: 'CalendarMaster', icon: 'CalendarDays', desc: 'Schedules and plans content calendars', status: 'busy', category: 'Social' },
  { id: 'communitymanager', name: 'CommunityManager', icon: 'MessageSquare', desc: 'Engages with audience and handles DMs', status: 'online', category: 'Social' },
  { id: 'brandstrategist', name: 'BrandStrategist', icon: 'Target', desc: 'Develops brand positioning and voice', status: 'online', category: 'Strategy' },
  { id: 'competitortracker', name: 'CompetitorTracker', icon: 'Eye', desc: 'Monitors competitor activity and intel', status: 'offline', category: 'Strategy' },
  { id: 'analyticspro', name: 'AnalyticsPro', icon: 'BarChart3', desc: 'Generates performance reports and insights', status: 'online', category: 'Strategy' },
  { id: 'creativegenius', name: 'CreativeGenius', icon: 'Sparkles', desc: 'Generates creative concepts and ideas', status: 'online', category: 'Creative' },
  { id: 'photoshooter', name: 'PhotoShooter', icon: 'Camera', desc: 'Edits and enhances visual assets', status: 'busy', category: 'Creative' },
  { id: 'videodirector', name: 'VideoDirector', icon: 'Film', desc: 'Produces and edits video content', status: 'offline', category: 'Creative' },
  { id: 'agencymanager', name: 'AgencyManager', icon: 'Briefcase', desc: 'Coordinates overall agency operations', status: 'online', category: 'Management' },
  { id: 'qualitychecker', name: 'QualityChecker', icon: 'Shield', desc: 'Reviews deliverables for quality standards', status: 'online', category: 'Management' },
  { id: 'leadhunterpro', name: 'LeadHunterPro', icon: 'UserPlus', desc: 'Identifies and qualifies new leads', status: 'busy', category: 'Management' },
  { id: 'crisismanager', name: 'CrisisManager', icon: 'AlertCircle', desc: 'Handles escalations and crisis comms', status: 'offline', category: 'Management' },
  { id: 'clientintake', name: 'ClientIntake', icon: 'ClipboardCheck', desc: 'Onboards new clients and gathers briefs', status: 'online', category: 'Management' },
  { id: 'abtester', name: 'ABTester', icon: 'FileText', desc: 'Runs A/B tests on campaigns and assets', status: 'offline', category: 'Management' },
  { id: 'reviewanalyst', name: 'ReviewAnalyst', icon: 'Eye', desc: 'Analyzes reviews and sentiment data', status: 'online', category: 'Management' },
]

export const mockAgentCategories = [
  {
    name: 'Team',
    icon: 'Users',
    agents: ['openclaw', 'hermes', 'aca', 'opencode'],
    description: 'OpenClaw → Hermes → ACA (CEO) → Agency Agents (19) → Hermes → Client',
  },
  {
    name: 'Content',
    icon: 'PenTool',
    agents: ['contentwriter', 'emailwizard', 'seomaster'],
  },
  {
    name: 'Social',
    icon: 'Globe',
    agents: ['socialcommander', 'calendarmaster', 'communitymanager'],
  },
  {
    name: 'Strategy',
    icon: 'Target',
    agents: ['brandstrategist', 'competitortracker', 'analyticspro'],
  },
  {
    name: 'Creative',
    icon: 'Sparkles',
    agents: ['creativegenius', 'photoshooter', 'videodirector'],
  },
  {
    name: 'Management',
    icon: 'Briefcase',
    agents: ['agencymanager', 'qualitychecker', 'leadhunterpro', 'crisismanager', 'clientintake', 'abtester', 'reviewanalyst'],
  },
]

export const mockAgentWelcomeMessages = {
  openclaw: "I'm OpenClaw, your Lead Generation Agent. I search Google, LinkedIn, Twitter, and directories for global leads. Tell me what industry to target!",
  hermes: "I'm Hermes, your Client Management Agent. I send cold emails (with OpenClaw's research), onboard clients, gather requirements, and pass to ACA for agent assignment.",
  aca: "I'm ACA, the Agency Coordination Agent (CEO Agent). Hermes sends me client requirements, and I analyze which of our 19 agency agents should work on it. I assign tasks to the best-fit agents.",
  opencode: "I'm OpenCode, the Agency Core Agent. I build full marketing packages — social content, blogs, emails, ads, video scripts, website copy. ACA tells me what to build.",
  contentwriter: "I'm ready to craft compelling content for your clients. Share a topic, audience, and tone, and I'll produce drafts that convert.",
  emailwizard: "Email campaigns are my specialty. Give me a goal and audience, and I'll design sequences that drive opens and clicks.",
  seomaster: "Let's boost your clients' search visibility. Share a URL or keyword target and I'll audit and optimize.",
  socialcommander: "I manage your entire social presence. Tell me which platform and I'll schedule, post, and engage.",
  calendarmaster: "Need a content calendar? I'll plan weeks ahead so nothing slips through the cracks.",
  communitymanager: "I keep your communities thriving. Share a thread or comment that needs attention.",
  brandstrategist: "Brand strategy is my domain. Let's define positioning, voice, and visual identity for your clients.",
  competitortracker: "I watch the competition so you don't have to. Ask me for the latest intel on any competitor.",
  analyticspro: "Data tells the story. I'll generate reports, charts, and insights from your campaign performance.",
  creativegenius: "Creativity is my middle name. Give me a brief and I'll brainstorm concepts that break through the noise.",
  photoshooter: "Visuals are everything. Send me raw assets and I'll edit them to perfection.",
  videodirector: "Video content drives engagement. Share a concept and I'll plan the production from storyboard to export.",
  agencymanager: "I oversee all agency operations. Need a status update on any department? Just ask.",
  qualitychecker: "Quality is non-negotiable. Send me deliverables and I'll review them against your standards.",
  leadhunterpro: "I'm always hunting for the next opportunity. Tell me your ICP and I'll find matching leads.",
  crisismanager: "When things go wrong, I stay calm. Describe the situation and I'll draft a response plan.",
  clientintake: "New clients are exciting! Send me their info and I'll create a comprehensive onboarding brief.",
  abtester: "Data-driven decisions win. Give me two variants and I'll set up a statistically sound test.",
  reviewanalyst: "Reviews are gold. Share a client's review page and I'll extract actionable insights.",
}

export const mockAgentQuickActions = {
  contentwriter: ['Write Blog Post', 'Draft Email', 'SEO Optimize', 'Create Brief'],
  emailwizard: ['Campaign Strategy', 'Write Sequence', 'Subject Line A/B', 'Welcome Email'],
  seomaster: ['Audit URL', 'Keyword Research', 'Meta Tags', 'Content Gap'],
  socialcommander: ['Schedule Posts', 'Platform Audit', 'Engagement Report', 'Hashtag Research'],
  calendarmaster: ['Monthly Plan', 'Weekly Schedule', 'Theme Days', 'Content Mix'],
  communitymanager: ['Reply to Thread', 'Crisis Check', 'Engagement Metrics', 'FAQ Draft'],
  brandstrategist: ['Brand Audit', 'Voice Guidelines', 'Positioning Doc', 'Mood Board'],
  competitortracker: ['Competitor Intel', 'Market Scan', 'SWOT Analysis', 'Price Check'],
  analyticspro: ['Weekly Report', 'Campaign Analysis', 'ROI Calculator', 'Trend Report'],
  creativegenius: ['Brainstorm Session', 'Concept Board', 'Tagline Ideas', 'Visual Direction'],
  photoshooter: ['Edit Assets', 'Color Grade', 'Batch Process', 'Asset Library'],
  videodirector: ['Storyboard', 'Script Write', 'Edit Timeline', 'Thumbnail Design'],
  agencymanager: ['Operations Review', 'Resource Plan', 'Status Report', 'Team Sync'],
  qualitychecker: ['Review Deliverable', 'Checklist Run', 'Compliance Audit', 'Feedback Notes'],
  leadhunterpro: ['Find Leads', 'Score Leads', 'Outreach Draft', 'List Clean'],
  crisismanager: ['Response Plan', 'Stakeholder Comms', 'Timeline', 'Post-Mortem'],
  clientintake: ['Create Brief', 'Onboard Client', 'Gather Assets', 'Kickoff Plan'],
  abtester: ['Design Test', 'Review Results', 'Hypothesis Draft', 'Sample Size Calc'],
  reviewanalyst: ['Sentiment Report', 'Trend Analysis', 'Competitor Reviews', 'Response Draft'],
}

export const mockWorkflows = [
  {
    id: 'wf-1',
    name: 'Social Media Campaign',
    description: 'Automated social media posting and engagement across platforms',
    client: 'FitZone Gym',
    status: 'running',
    progress: 72,
    lastRun: '2 hours ago',
    phases: [
      { name: 'Content Creation', status: 'completed', progress: 100 },
      { name: 'Scheduling', status: 'completed', progress: 100 },
      { name: 'Publishing', status: 'running', progress: 65 },
      { name: 'Engagement Monitoring', status: 'pending', progress: 0 },
    ],
  },
  {
    id: 'wf-2',
    name: 'Blog Content Pipeline',
    description: 'End-to-end blog content generation and publishing workflow',
    client: 'Urban Cafe',
    status: 'running',
    progress: 65,
    lastRun: '1 day ago',
    phases: [
      { name: 'Topic Research', status: 'completed', progress: 100 },
      { name: 'Drafting', status: 'completed', progress: 100 },
      { name: 'Editing', status: 'running', progress: 60 },
      { name: 'SEO Optimization', status: 'running', progress: 30 },
      { name: 'Publishing', status: 'pending', progress: 0 },
    ],
  },
  {
    id: 'wf-3',
    name: 'Drip Email Sequence',
    description: 'Automated email nurture sequence for lead conversion',
    client: 'TechFlow SaaS',
    status: 'paused',
    progress: 78,
    lastRun: '3 days ago',
    phases: [
      { name: 'Audience Segmentation', status: 'completed', progress: 100 },
      { name: 'Email Copywriting', status: 'completed', progress: 100 },
      { name: 'A/B Testing', status: 'completed', progress: 100 },
      { name: 'Deployment', status: 'paused', progress: 45 },
    ],
  },
  {
    id: 'wf-4',
    name: 'Instagram Automation',
    description: 'Automated Instagram posting, stories, and engagement',
    client: 'Bloom Beauty',
    status: 'running',
    progress: 71,
    lastRun: '1 hour ago',
    phases: [
      { name: 'Visual Asset Creation', status: 'completed', progress: 100 },
      { name: 'Caption Writing', status: 'completed', progress: 100 },
      { name: 'Scheduling', status: 'running', progress: 80 },
      { name: 'Engagement Tracking', status: 'running', progress: 40 },
    ],
  },
  {
    id: 'wf-5',
    name: 'Workflow Setup',
    description: 'Initial workflow configuration and onboarding',
    client: 'PeakPerformance',
    status: 'running',
    progress: 23,
    lastRun: 'Just now',
    phases: [
      { name: 'Client Brief', status: 'completed', progress: 100 },
      { name: 'Platform Integration', status: 'running', progress: 30 },
      { name: 'Content Strategy', status: 'pending', progress: 0 },
      { name: 'Campaign Setup', status: 'pending', progress: 0 },
    ],
  },
  {
    id: 'wf-6',
    name: 'Email Newsletter',
    description: 'Weekly email newsletter automation',
    client: 'GreenLeaf Organics',
    status: 'running',
    progress: 35,
    lastRun: '2 days ago',
    phases: [
      { name: 'Content Curation', status: 'completed', progress: 100 },
      { name: 'Template Design', status: 'running', progress: 60 },
      { name: 'Audience Targeting', status: 'pending', progress: 0 },
      { name: 'Send & Analyze', status: 'pending', progress: 0 },
    ],
  },
  {
    id: 'wf-7',
    name: 'LinkedIn Outreach',
    description: 'Automated LinkedIn connection and messaging campaign',
    client: 'TechFlow SaaS',
    status: 'paused',
    progress: 34,
    lastRun: '1 week ago',
    phases: [
      { name: 'Profile Targeting', status: 'completed', progress: 100 },
      { name: 'Message Templates', status: 'completed', progress: 100 },
      { name: 'Connection Requests', status: 'paused', progress: 20 },
      { name: 'Follow-up Sequence', status: 'pending', progress: 0 },
    ],
  },
  {
    id: 'wf-8',
    name: 'Influencer Outreach',
    description: 'Identify, contact, and manage influencer partnerships',
    client: 'Bloom Beauty',
    status: 'running',
    progress: 55,
    lastRun: '5 hours ago',
    phases: [
      { name: 'Influencer Discovery', status: 'completed', progress: 100 },
      { name: 'Outreach Drafting', status: 'completed', progress: 100 },
      { name: 'Partnership Negotiation', status: 'running', progress: 40 },
      { name: 'Campaign Execution', status: 'pending', progress: 0 },
    ],
  },
  {
    id: 'wf-9',
    name: 'Quarterly Review',
    description: 'Generate quarterly performance reports for all clients',
    client: 'All Clients',
    status: 'pending',
    progress: 0,
    lastRun: 'N/A',
    phases: [
      { name: 'Data Collection', status: 'pending', progress: 0 },
      { name: 'Analysis', status: 'pending', progress: 0 },
      { name: 'Report Generation', status: 'pending', progress: 0 },
      { name: 'Client Review', status: 'pending', progress: 0 },
    ],
  },
]

export const mockDashboardStats = {
  activeClients: 24,
  workflowsRunning: 18,
  contentGenerated: 342,
  revenue: 84750,
  trendActiveClients: '+12%',
  trendWorkflows: '+8%',
  trendContent: '+23%',
  trendRevenue: '+18%',
}

export const mockRecentActivity = [
  { action: 'Blog post generated for FitZone Gym', time: '12 min ago', type: 'content' },
  { action: 'Workflow completed for Urban Cafe', time: '34 min ago', type: 'workflow' },
  { action: 'Weekly report exported for TechFlow SaaS', time: '1 hr ago', type: 'report' },
  { action: 'New client onboarded: Bloom Beauty', time: '2 hr ago', type: 'client' },
  { action: 'CEO chat session completed', time: '3 hr ago', type: 'chat' },
  { action: 'Social campaign launched for GreenLeaf Organics', time: '5 hr ago', type: 'content' },
  { action: 'Email sequence optimized for FitZone Gym', time: '6 hr ago', type: 'workflow' },
  { action: 'Analytics report generated for Urban Cafe', time: '8 hr ago', type: 'report' },
]

export const mockReports = [
  { id: '1', client: 'FitZone Gym', type: 'Weekly', date: '2026-05-11', status: 'generated', metrics: { impressions: '12.4K', clicks: '892', conversions: '64' } },
  { id: '2', client: 'Urban Cafe', type: 'Monthly', date: '2026-05-10', status: 'generated', metrics: { impressions: '8.2K', clicks: '534', conversions: '41' } },
  { id: '3', client: 'TechFlow SaaS', type: 'Weekly', date: '2026-05-08', status: 'pending', metrics: null },
  { id: '4', client: 'Bloom Beauty', type: 'Monthly', date: '2026-05-05', status: 'generated', metrics: { impressions: '18.7K', clicks: '1,245', conversions: '98' } },
  { id: '5', client: 'PeakPerformance', type: 'Weekly', date: '2026-05-04', status: 'pending', metrics: null },
  { id: '6', client: 'GreenLeaf Organics', type: 'Monthly', date: '2026-05-01', status: 'generated', metrics: { impressions: '6.3K', clicks: '412', conversions: '29' } },
]

export const mockAgentChatResponses = {
  contentwriter: [
    "I've drafted a blog post outline for your review. It covers the key topics with SEO-optimized headers and a compelling narrative arc.",
    "Here's a piece of web copy that speaks directly to your target audience. The tone is conversational yet authoritative.",
    "I've analyzed your existing content and have suggestions for improvement. Want me to create a content optimization plan?",
  ],
  emailwizard: [
    "I've designed a 5-email welcome sequence that nurtures subscribers from signup to first purchase. Each email has a specific goal and CTA.",
    "Here's an A/B test proposal for your subject lines. Version A uses curiosity gaps, version B uses benefit-driven language.",
    "Your email campaign performance analysis is ready. I've identified the top-performing segments and recommended optimizations.",
  ],
  seomaster: [
    "I've completed an SEO audit of your URL. There are 12 optimization opportunities including meta descriptions, header structure, and keyword density.",
    "Here's a keyword research report with 30 high-potential terms ranked by search volume and competition level.",
    "Your content gap analysis is ready. I've identified 8 topics your competitors are ranking for that you haven't covered yet.",
  ],
  socialcommander: [
    "I've scheduled this week's social media posts across all platforms. The content mix includes educational, promotional, and engagement-driving posts.",
    "Here's a platform audit report. Your Instagram engagement is up 15% this month, but LinkedIn needs more consistent posting.",
    "I've researched 20 trending hashtags in your niche. Adding these to your posts could increase reach by an estimated 30%.",
  ],
}

export const mockCEOAgentResponses = {
  greeting: ["Hello! I'm your CEO Agent. I can help you manage clients, run workflows, assign agents, and generate reports. What would you like to do today?"],
  newClient: [
    "I'll start the client onboarding process. Let me gather the initial brief and set up the workspace.",
    "Creating a new client profile. I'll need their company name, industry, contact details, and a brief description of their goals.",
    "New client intake initiated. I've prepared the onboarding questionnaire and will begin the discovery phase.",
  ],
  workflow: [
    "I've identified the best workflow for this task. Let me configure and deploy it now.",
    "Analyzing your requirements and matching them to our available workflow templates. I'll have a recommendation shortly.",
    "Workflow deployment started. I'll monitor the progress and alert you when each phase completes.",
  ],
  report: [
    "Generating a comprehensive performance report. I'll include key metrics, trends, and actionable recommendations.",
    "Pulling data from all active campaigns to create your report. This will include engagement stats, ROI analysis, and growth opportunities.",
    "Report generation in progress. I'm aggregating data from analytics, social platforms, and campaign managers for a 360-degree view.",
  ],
  status: [
    "Here's your agency status: 24 active clients, 18 workflows running, 342 content pieces generated this month. Revenue is up 18%.",
    "Current snapshot: All systems operational. 12 agents online, 3 busy, 4 offline. 2 workflows need attention.",
    "Agency health check complete. Client satisfaction is at 94%. Average campaign ROI is 3.2x. 5 deliverables due this week.",
  ],
  help: [
    "Here's what I can do for you:\n• 'New Client' - Start onboarding a new client\n• 'Run Workflow' - Deploy a workflow for any client\n• 'Generate Report' - Create performance reports\n• 'Agent Status' - Check agent availability\n• 'Dashboard' - View agency metrics",
    "I'm your AI agency manager. Try commands like 'Create client for Bloom Beauty', 'Run social campaign for FitZone', or 'Show me the dashboard'.",
  ],
  default: [
    "I understand your request. Let me analyze the situation and determine the best course of action for your agency.",
    "Processing your command. I'll coordinate with the relevant agents and systems to get this done efficiently.",
    "Got it. I'm working on this now and will keep you updated on progress. Is there anything else you need?",
  ],
}

export const mockCEOCommands = {
  'new client': { action: 'createClient', description: 'Start client onboarding process' },
  'create client': { action: 'createClient', description: 'Start client onboarding process' },
  'add client': { action: 'createClient', description: 'Start client onboarding process' },
  'run workflow': { action: 'runWorkflow', description: 'Deploy a workflow for a client' },
  'start workflow': { action: 'runWorkflow', description: 'Deploy a workflow for a client' },
  'deploy workflow': { action: 'runWorkflow', description: 'Deploy a workflow for a client' },
  'generate report': { action: 'generateReport', description: 'Create a performance report' },
  'create report': { action: 'generateReport', description: 'Create a performance report' },
  'agent status': { action: 'agentStatus', description: 'Check agent team status' },
  'status': { action: 'agentStatus', description: 'Check agent team status' },
  'dashboard': { action: 'dashboard', description: 'View agency dashboard metrics' },
  'show dashboard': { action: 'dashboard', description: 'View agency dashboard metrics' },
  'help': { action: 'help', description: 'Show available commands' },
  'what can you do': { action: 'help', description: 'Show available commands' },
}

export const mockNotifications = [
  { id: 'n1', title: 'Campaign Alert', description: 'Q4 LinkedIn campaign performance dropped 12%', time: '5m ago', type: 'alert' },
  { id: 'n2', title: 'New Client', description: 'TechVista Inc. just onboarded', time: '1h ago', type: 'client' },
  { id: 'n3', title: 'Report Ready', description: 'Monthly analytics report is available', time: '2h ago', type: 'report' },
  { id: 'n4', title: 'Workflow Complete', description: 'Blog pipeline finished for Urban Cafe', time: '3h ago', type: 'workflow' },
  { id: 'n5', title: 'Agent Offline', description: 'VideoDirector went offline unexpectedly', time: '4h ago', type: 'alert' },
]
