import { NextResponse } from 'next/server'

export const dynamic = 'force-dynamic'

// Content Creator — generates blog/social/ad/email drafts from a brief
// Spec: marketing-ai-agency/agents/content-creator.md
export async function POST(request) {
  try {
    const body = await request.json().catch(() => ({}))
    const message = (body.message || body.brief || '').toString().trim()
    const format = (body.format || 'blog').toString().toLowerCase() // blog | social | ad | email

    if (!message) {
      return NextResponse.json(
        { success: false, error: 'A brief is required. Example: { message: "Write a 600-word blog intro about AI marketing for SaaS founders" }' },
        { status: 400 }
      )
    }

    const stamp = new Date().toISOString()

    const templates = {
      blog: `# ${titleize(message)}\n\n## Hook\n${hook(message)}\n\n## The problem\nMost teams in this space treat ${topic(message)} as a one-off project. It isn't. It's a system.\n\n## What to do this week\n1. Pick one channel and one offer.\n2. Run it for 14 days without changing the creative.\n3. Measure completion rate, not clicks.\n\n## Closing\nIf you want the long version, ping the agency desk — we'll send the full playbook.\n\n_(Generated by Content Creator at ${stamp}.)_`,
      social: `${hook(message)}\n\n→ Most teams overthink this.\n→ The winners ship daily and learn faster.\n\nWant the playbook? Comment "PLAYBOOK" and I'll send it over.\n\n#marketing #${hashtag(message)} #growth`,
      ad: `**Headline:** ${titleize(message)}\n**Primary text:** ${hook(message)} Most teams overthink this. The ones who win ship in days, not months.\n**CTA:** Start free →\n**Angle:** speed-over-perfection\n_(Generated at ${stamp})_`,
      email: `**Subject A:** Quick one on ${topic(message)}\n**Subject B:** Are you making this ${topic(message)} mistake?\n\nHey {{first_name}},\n\n${hook(message)}\n\n**Three things to do this week:**\n1. Audit your last 10 posts for hook strength.\n2. Pick one offer, one channel, one CTA.\n3. Ship daily for 14 days, no creative swaps.\n\n— NexusAI Agency\n\n_(Generated at ${stamp})_`,
    }

    const text = templates[format] || templates.blog

    return NextResponse.json({
      success: true,
      response: text,
      data: { agent: 'content-creator', format, brief: message, generated_at: stamp },
    })
  } catch (err) {
    return NextResponse.json(
      { success: false, error: err.message || 'Content generation failed' },
      { status: 500 }
    )
  }
}

function titleize(s) {
  return s.replace(/^./, (c) => c.toUpperCase()).slice(0, 80)
}
function hook(s) {
  return `Here's the thing about ${topic(s)}: speed beats polish. The teams that win ship daily, measure completion, and iterate on what worked — not what they wished worked.`
}
function topic(s) {
  return s.split(/\s+/).slice(0, 4).join(' ').toLowerCase()
}
function hashtag(s) {
  return s.split(/\s+/)[0].toLowerCase().replace(/[^a-z0-9]/g, '') || 'growth'
}
